#!/bin/bash
cd /srv/conda/lib/python3.6/site-packages/whitebox
wget https://www.whiteboxgeo.com/WBT_Linux/WhiteboxTools_linux_amd64.zip
tar -xvf WhiteboxTools_linux_amd64.tar.xz
mv WBT/whitebox_tools .
mkdir testdata
cd testdata
wget https://github.com/giswqs/whitebox-python/raw/master/examples/testdata/DEM.tif
wget https://github.com/giswqs/whitebox-python/raw/master/examples/testdata/DEM.dep